services:
  xray-server:
    image: teddysun/xray:{{ XRAY_TAG }}
    environment:
      - 'XRAY_VMESS_AEAD_FORCED=false'
      - 'xray.vmess.aead.forced=false'
    volumes:
      - '{{ mkdir(APP_PATH/"etc"/"xray") | chown }}:/etc/xray'
    networks:
      - nginx

networks:
  nginx:
    name: nginx
