services:
  xray_server:
    image: teddysun/xray:latest
    environment:
      - 'XRAY_VMESS_AEAD_FORCED=false'
      - 'xray.vmess.aead.forced=false'
    volumes:
      - '{{ container.get_app_path("etc", "xray") }}:/etc/xray'
    networks:
      - nginx

networks:
  nginx:
    name: nginx
