version: "3.9"

services:
  aliyun-ddns:
    image: sanjusss/aliyun-ddns
    restart: unless-stopped
    environment:
      AKID: "{{ ALI_DDNS_KEY }}"
      AKSCT: "{{ ALI_DDNS_SECRET }}"
      DOMAIN: "{{ ALI_DDNS_DOMAIN }}"
      ROOT_DOMAIN: "{{ ALI_DDNS_ROOT_DOMAIN }}"
      REDO: "300"
      TTL: "600"
      TIMEZONE: "8.0"
      TYPE: "A,AAAA"
      CHECKLOCAL: "{{ "true" if bool(ALI_DDNS_CHECKLOCAL) else "false" }}"
      IPV4NETS: "{{ ALI_DDNS_IPV4NETS }}"
      IPV6NETS: "{{ ALI_DDNS_IPV6NETS }}"
    {% if bool(ALI_DDNS_CHECKLOCAL) %}
    network_mode: host
    {% else %}
    networks:
      - aliyun-ddns
    {% endif %}
    logging:
      options:
        max-size: 1m

{% if not bool(ALI_DDNS_CHECKLOCAL) %}
networks:
  aliyun-ddns:
    name: aliyun-ddns
{% endif %}
