services:
  gemini-pro-chat:
    image: babaohuang/geminiprochat:{{ GEMINI_TAG }}
    environment:
      - 'GEMINI_API_KEY={{ GEMINI_API_KEY }}'
    networks:
      - nginx

networks:
  nginx:
    name: nginx
