version: "3.9"

services:
  gemini-pro-chat:
    container_name: gemini-pro-chat
    image: babaohuang/geminiprochat
    restart: unless-stopped
    environment:
      - GEMINI_API_KEY={{ GEMINI_API_KEY }}
    networks:
      - nginx
    logging:
      options:
        max-size: 1m

networks:
  nginx:
    name: nginx
