services:

  pypi-server:
    image: pypiserver/pypiserver:{{ PYPISERVER_TAG }}
#   {% if PYPISERVER_EXPOSE_PORT > 0 %}
    ports:
      - '{{ PYPISERVER_EXPOSE_PORT }}:8080'
#   {% endif %}
    volumes:
      - '{{ mkdir(APP_DATA_PATH/"auth") | chown }}:/data/auth'
      - '{{ mkdir(APP_DATA_PATH/"packages") | chown }}:/data/packages'
    command: run -P /data/auth/.htpasswd -a {{ PYPISERVER_AUTHENTICATE }} /data/packages
    networks:
      - nginx

networks:
  nginx:
    name: nginx
