services:

  pypiserver:
    image: pypiserver/pypiserver:{{ PYPISERVER_TAG }}
    #   {% if int(PYPISERVER_EXPOSE_PORT, default=0) > 0 %}
    ports:
      - '{{ PYPISERVER_EXPOSE_PORT }}:8080'
#   {% endif %}
    volumes:
      - '{{ container.get_app_data_path("auth") }}:/data/auth'
      - '{{ container.get_app_data_path("packages") }}:/data/packages'
    command: run -P /data/auth/.htpasswd -a update /data/packages
    networks:
      - nginx

networks:
  nginx:
    name: nginx
