services:
  aria2-pro:
    image: p3terx/aria2-pro
    environment:
      - 'PUID={{ DOCKER_UID }}'
      - 'PGID={{ DOCKER_GID }}'
      - 'UMASK_SET=022'
      - 'RPC_SECRET={{ ARIA2_RPC_SECRET }}'
      - 'RPC_PORT=6800'
      - 'LISTEN_PORT=6888'
#    {% if int(ARIA2_EXPOSE_PORT, 0) > 0 %}
    ports:
      - '{{ ARIA2_EXPOSE_PORT }}:6800'
#    {% endif %}
    volumes:
      - "{{ container.get_app_path("config") }}:/config'
      - '{{ container.get_download_path() }}:/downloads'
    networks:
      - nginx

networks:
  nginx:
    name: nginx
