services:
  aria2-pro:
    image: p3terx/aria2-pro:{{ ARIA2_TAG }}
    environment:
      - 'PUID={{ DOCKER_UID }}'
      - 'PGID={{ DOCKER_GID }}'
      - 'UMASK_SET=022'
      - 'RPC_SECRET={{ ARIA2_RPC_SECRET }}'
      - 'RPC_PORT=6800'
      - 'LISTEN_PORT=6888'
#    {% if ARIA2_EXPOSE_PORT > 0 %}
    ports:
      - '{{ ARIA2_EXPOSE_PORT }}:6800'
#    {% endif %}
    volumes:
      - '{{ mkdir(APP_PATH/"config") | chown(docker_user) }}:/config'
      - '{{ mkdir(DOWNLOAD_PATH) | chown(docker_user) }}:/downloads'
    networks:
      - nginx

networks:
  nginx:
    name: nginx
