services:
  gpt4free:
    image: hlohaus789/g4f:{{ GPT4FREE_TAG }}
    shm_size: '2gb'
    volumes:
      - '{{ mkdir(APP_PATH/"hardir") | chown }}:/app/hardir'
    networks:
      - nginx

networks:
  nginx:
    name: nginx
