services:
  code-server:
    user: '{{ DOCKER_PUID }}:{{ DOCKER_PGID }}'
    environment:
      - 'TZ=Etc/UTC'
      - 'PASSWORD={{ VSCODE_PASSWORD }}'
#   {% if int(VSCODE_EXPOSE_PORT, 0) > 0 %}
    ports:
      - '{{ VSCODE_EXPOSE_PORT }}:8080'
#   {% endif %}
    volumes:
      - '{{ container.get_app_path("home") }}:/home/coder'
      - '{{ container.get_app_data_path("project") }}:/home/coder/project'
    networks:
      - nginx

networks:
  nginx:
    name: nginx
