services:
  gitlab:
    image: gitlab/gitlab-ce:{{ GITLAB_TAG }}
    environment:
      GITLAB_ROOT_PASSWORD: '{{ GITLAB_ROOT_PASSWORD }}'
      GITLAB_OMNIBUS_CONFIG: |
          external_url 'https://{{ GITLAB_DOMAIN }}:{{ HTTPS_PORT }}'
          gitlab_rails['gitlab_shell_ssh_port'] = {{ GITLAB_SSH_PORT }}

          nginx['enable'] = true
          nginx['listen_port'] = 80
          nginx['listen_https'] = false

          letsencrypt['enable'] = false
          registry['enable'] = false

          # 关闭监控
          prometheus['enable'] = false
          alertmanager['enable'] = false
          node_exporter['enable'] = false
          redis_exporter['enable'] = false
          postgres_exporter['enable'] = false
          pgbouncer_exporter['enable'] = false
          gitlab_exporter['enable'] = false
          prometheus_monitoring['enable'] = false
          grafana['enable'] = false
          sidekiq['metrics_enabled'] = false

          # 禁用 PUMA 集群模式
          puma['worker_processes'] = 0
          puma['min_threads'] = 1
          puma['max_threads'] = 2

          # 降低后台守护进程并发数
          sidekiq['max_concurrency'] = 5

          gitlab_ci['gitlab_ci_all_broken_builds'] = false
          gitlab_ci['gitlab_ci_add_pusher'] = false

          # Usage Statistics
          gitlab_rails['usage_ping_enabled'] = false
          gitlab_rails['sentry_enabled'] = false
          grafana['reporting_enabled'] = false

    ports:
      - '{{ GITLAB_SSH_PORT }}:22'
    volumes:
      - '{{ container.get_app_path("config") }}:/etc/gitlab'
      - '{{ container.get_app_path("logs") }}:/var/log/gitlab'
      - '{{ container.get_app_path("data") }}:/var/opt/gitlab'
      - '{{ container.get_app_data_path("data", "git-data") }}:/var/opt/gitlab/git-data'
    networks:
      - nginx


networks:
  nginx:
    name: nginx
