services:
  onlyoffice-server:
    image: onlyoffice/documentserver:{{ ONLYOFFICE_SERVER_TAG }}
#   {% if int(ONLYOFFICE_SERVER_EXPOSE_PORT, 0) > 0 %}
    ports:
      - '{{ ONLYOFFICE_SERVER_EXPOSE_PORT }}:80'
#   {% endif %}
    environment:
      - 'ONLYOFFICE_HTTPS_HSTS_ENABLED=false'
      - 'JWT_ENABLED=true'
      - 'JWT_SECRET={{ ONLYOFFICE_SERVER_JWT_SECRET }}'
    volumes:
      - '{{ container.get_app_data_path("data") }}:/var/www/onlyoffice/Data'
      - '{{ container.get_app_data_path("logs") }}:/var/log/onlyoffice'
    networks:
      - nginx

networks:
  nginx:
    name: nginx
