services:
  openwrt_builder:
    image: p3terx/openwrt-build-env:latest
    user: '{{ DOCKER_UID }}:{{ DOCKER_GID }}'
    volumes:
      - '{{ path(OPENWRT_BUILD_PATH) }}:/home/user/openwrt'
      - '{{ container.get_path("configs") }}:/home/user/configs'
      - '{{ container.get_path("patchs") }}:/home/user/patchs'
    working_dir: "/home/user/openwrt"
    networks:
      - build

networks:
  build:
    name: build
