services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:{{ QBITTORRENT_TAG }}
    environment:
      - 'PUID={{ DOCKER_UID }}'
      - 'PGID={{ DOCKER_GID }}'
      - 'TZ=Etc/UTC'
      - 'WEBUI_PORT=8080'
      - 'TORRENTING_PORT={{ QBITTORRENT_TORRENTING_PORT }}'
    volumes:
      - '{{ mkdir(APP_PATH/"config") | chown(docker_user) }}:/config'
      - '{{ mkdir(DOWNLOAD_PATH/"qbittorrent") | chown(docker_user) }}:/downloads'
#   {% if QBITTORRENT_EXPOSE_PORT > 0 %}
    ports:
      - '{{ QBITTORRENT_EXPOSE_PORT }}:8080'
      - '{{ QBITTORRENT_TORRENTING_PORT }}:{{ QBITTORRENT_TORRENTING_PORT }}'
      - '{{ QBITTORRENT_TORRENTING_PORT }}:{{ QBITTORRENT_TORRENTING_PORT }}/udp'
#   {% endif %}
    networks:
      - nginx

networks:
  nginx:
    name: nginx
