services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:{{ QBITTORRENT_TAG }}
    environment:
      - 'PUID={{ DOCKER_UID }}'
      - 'PGID={{ DOCKER_GID }}'
      - 'TZ=Etc/UTC'
      - 'WEBUI_PORT=8080'
      - 'TORRENTING_PORT={{ int(QBITTORRENT_TORRENTING_PORT) }}'
    volumes:
      - '{{ container.get_app_path("config") }}:/config'
      - '{{ container.get_download_path("qbittorrent") }}:/downloads'
#   {% if int(QBITTORRENT_EXPOSE_PORT, 0) > 0 %}
    ports:
      - '{{ int(QBITTORRENT_EXPOSE_PORT) }}:8080'
      - '{{ int(QBITTORRENT_TORRENTING_PORT) }}:{{ int(QBITTORRENT_TORRENTING_PORT) }}'
      - '{{ int(QBITTORRENT_TORRENTING_PORT) }}:{{ int(QBITTORRENT_TORRENTING_PORT) }}/udp'
#   {% endif %}
    networks:
      - nginx

networks:
  nginx:
    name: nginx
