version: "3.9"

services:

  nextcloud:
    container_name: nextcloud
    build:
      context: "{{ container.get_path() }}"
      dockerfile: "{{ container.get_docker_file_path() }}"
    user: "{{ DOCKER_PUID }}:{{ DOCKER_PGID }}"
    restart: unless-stopped
    environment:
      - "MYSQL_DATABASE={{ NEXTCLOUD_MYSQL_DATABASE }}"
      - "MYSQL_USER={{ NEXTCLOUD_MYSQL_USER }}"
      - "MYSQL_PASSWORD={{ NEXTCLOUD_MYSQL_PASSWORD }}"
      - "MYSQL_HOST=nextcloud_mariadb:3306"
      - "NEXTCLOUD_TRUSTED_DOMAINS={{ NEXTCLOUD_DOMAIN }}"
      - "OVERWRITEPROTOCOL=https"
      - "OVERWRITEHOST={{ NEXTCLOUD_DOMAIN }}:{{ HTTPS_PORT }}"
      - "OVERWRITECLIURL=https://{{ NEXTCLOUD_DOMAIN }}:{{ HTTPS_PORT }}"
      - "REDIS_HOST=nextcloud_redis"
      - "REDIS_PORT=6379"
      - "REDIS_HOST_PASSWORD=nextcloud_redis_pass"
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0 # Allow an unprivileged user to listen on any port (https://github.com/nextcloud/docker/issues/359)
    volumes:
      - "{{ container.get_app_path() }}/html:/var/www/html"
      - "{{ container.get_app_path() }}/data:/var/www/html/data"
      - "{{ container.get_user_data_path() }}:/data"
      - "{{ container.get_download_path() }}:/downloads"
    networks:
      - nextcloud
      - nginx
    depends_on:
      - nextcloud_mariadb
      - nextcloud_redis
    logging:
      options:
        max-size: 1m

  nextcloud_mariadb:
    container_name: nextcloud_mariadb
    image: mariadb
    user: "{{ DOCKER_PUID }}:{{ DOCKER_PGID }}"
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --log-bin=ROW --innodb-read-only-compressed=OFF
    environment:
      - MYSQL_ROOT_PASSWORD={{ NEXTCLOUD_MYSQL_ROOT_PASSWORD }}
      - MYSQL_DATABASE={{ NEXTCLOUD_MYSQL_DATABASE }}
      - MYSQL_USER={{ NEXTCLOUD_MYSQL_USER }}
      - MYSQL_PASSWORD={{ NEXTCLOUD_MYSQL_PASSWORD }}
    # ports:
    #   - 3306:3306
    volumes:
      - "{{ container.get_app_path() }}/mariadb:/var/lib/mysql"
    networks:
      - nextcloud
    logging:
      options:
        max-size: 1m

  nextcloud_redis:
    container_name: nextcloud_redis
    image: redis
    restart: unless-stopped
    command: redis-server --requirepass nextcloud_redis_pass
    networks:
      - nextcloud
    logging:
      options:
        max-size: 1m

networks:
  nginx:
    name: nginx
  nextcloud:
    name: nextcloud
