services:
  collabora-server:
    image: collabora/code
#   {% if int(COLLABORA_SERVER_EXPOSE_PORT, 0) > 0 %}
    ports:
      - '{{ COLLABORA_SERVER_EXPOSE_PORT }}:9980'
#   {% endif %}
    environment:
      - 'password={{ COLLABORA_SERVER_PASSWORD }}'
      - 'username={{ COLLABORA_SERVER_USERNAME }}'
      - 'domain={{ COLLABORA_SERVER_DOMAIN }}'
    networks:
      - nginx

networks:
  nginx:
    name: nginx
