services:
  proxy_pool:
    image: jhao104/proxy_pool
#   {% if int(PROXY_POOL_EXPOSE_PORT, default=0) > 0 %}
    ports:
      - '{{ PROXY_POOL_EXPOSE_PORT }}:5010'
#   {% endif %}
    links:
      - proxy_redis
    environment:
      - DB_CONN=redis://@proxy_redis:6379/0
    networks:
      - nginx
      - proxy_pool

  proxy_redis:
    image: redis
    networks:
      - proxy_pool

networks:
  nginx:
    name: nginx
  proxy_pool:
    name: proxy_pool
